# Generated by Django 4.0.4 on 2022-04-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('edition', models.IntegerField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=250)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
